bind r source-file ~/.tmux.conf
set -g base-index 1
set -g mouse on
set -g set-clipboard on

set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -sg escape-time 0

# styling
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=color2,bg=default"
set -g status-left "#[fg=color2,bold]  #S #[fg=color2,nobold] | "
set -g window-status-current-format "#[fg=color6,nobold] #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format " #I:#W"
set -g mode-style "fg=#1E2326 , bg=color2"
set -g message-style "fg=#D3C6AA,bg=default"
set -g pane-border-style "fg=color0"
set -g pane-active-border-style "fg=color2"
set -g status-right ""

#keybinds
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind b split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

set-window-option -g mode-keys vi
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# ctrl + h,j,k,l movement working with nvim, need nvim plugin to move out of nvim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# and in copy mode
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# rezising
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# copy 
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# switching windows
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
